name: Deploy and Run DAB

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'databricks.yml'

jobs:
  deploy:
    name: "Deploy Asset Bundle"
    runs-on: ubuntu-latest

    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Databricks CLI
        uses: databricks/setup-cli@v1

      - name: Validate Asset Bundle
        run: databricks bundle validate

      - name: Deploy Asset Bundle
        run: databricks bundle deploy --target dev

      - name: Run Databricks Job
        run: databricks bundle run write_test_data_job --target dev

